- name: Play With << All >> Hosts
  hosts: all
  roles:
    - { role: disk, tags: "disk", become: yes}
    
  tasks:
    - name: Inform check mode
      fail:
        msg: "Warning: Applied in check mode"
      ignore_errors: True
      when: ansible_check_mode
      tags:
        - always
