- name: Check SSH connnection
  hosts: all
  gather_facts: no
  tasks:
    - name: Test SSH connection credentials
      run_once: true
      ansible.builtin.ping:
      tags:
        - always

- name: Play With << All >> Hosts
  hosts: all
  roles:
    - { role: disk, tags: "disk", become: yes}
    - { role: timesyncd, tags: "timesyncd", become: yes}
    - { role: services, tags: "services", become: yes}
    - { role: network, tags: "network", become: yes}
    - { role: resource, tags: "resource", become: yes}
    - { role: splunk, tags: "splunk", become: yes}
    - { role: access_check, tags: "access_check", become: yes}
  tasks:
    - name: Inform check mode
      fail:
        msg: "Warning: Applied in check mode"
      ignore_errors: True
      when: ansible_check_mode
      tags:
        - always
