- name: Journald configuration
  include_tasks:
    file: journald.yml
    apply:
      tags:
        - services_journald
  tags:
    - services_journald
- name: Kaspersky service
  include_tasks:
    file: kaspersky.yml
    apply:
      tags:
        - services_kaspersky
  tags:
    - services_kaspersky